dist: xenial
language: node_js
node_js:
      - 6
      - 8
      - 10
services:
  - mysql
  
cache: yarn

# Don't run builds for renovate PRs, only renovate pushes
if: NOT branch =~ /^renovate\\/.+$/ AND type != pull_request

env:
  matrix:
    - DB=sqlite3 NODE_ENV=testing
    - DB=mysql NODE_ENV=testing-mysql

before_install:
  - if [ $DB == "mysql" ]; then mysql -e 'create database km_testing'; fi
